### ISSUE TITLE
Please add a 32-bit build 

### ISSUE THREAD

**Issue by swinokur** [mirsella/magisk-vim-ndk#1]
Hey there,
Thanks so much for doing this module! On my phone (LG G7, running Pie) I needed the 32-bit version of VIM not the 64 bit. (I checked the nano-ndk module - that uses the 32-bit version of nano).

It wasn't a big effort to grab the 32-bit build from the cross-compiled-binaries repo, rename it and replace it in the archive. 
But for some other folks - that might be too much? 

Anyway if it is easy to have an auto-build do both 32 and 64 bit versions that'd be nice!

thanks!

**Comment by mirsella** [comment]
Hey, sorry for the late response. Bravo on updating the binary yourself. But apart from older device, 32bit is dead and is not a preoccupation in the future. But you can fork this repo and put the 32bit version on it. i can put a link to it on my readme if you want :)
